services:
  all-in-one:
    build:
      context: ./../../  # Adjust this path as necessary
      dockerfile: Dockerfile.all-in-one
    platform: linux/amd64  # Specify target architecture for the build
    container_name: all-in-one
    image: oreoro/urban4:latest  # Image name and tag
    ports:
      - "8123:80"  # Map port 80 in the container to port 8123 on the host
    environment:
      - VITE_FRONTEND_URL=${VITE_FRONTEND_URL}
      - VITE_API_URL_CLIENT=${VITE_API_URL_CLIENT}
      - VITE_API_URL_SERVER=${VITE_API_URL_SERVER}
      - VITE_STRIPE_PUBLISHABLE_KEY=${VITE_STRIPE_PUBLISHABLE_KEY}
      - LOG_CHANNEL=${LOG_CHANNEL}
      - QUEUE_CONNECTION=${QUEUE_CONNECTION}
      - MAIL_MAILER=${MAIL_MAILER}
      - APP_KEY=${APP_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - FILESYSTEM_PUBLIC_DISK=${FILESYSTEM_PUBLIC_DISK}
      - FILESYSTEM_PRIVATE_DISK=${FILESYSTEM_PRIVATE_DISK}
      - APP_CDN_URL=${APP_CDN_URL}
      - DATABASE_URL=postgresql://postgres:secret@postgres:5432/hi-events

    depends_on:
      - postgres

  postgres:
    image: postgres:latest  # Use the latest version of PostgreSQL
    container_name: postgres
    environment:
      POSTGRES_DB: hi-events
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persist database data

volumes:
  pgdata:
